sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9dc66686a9e7_key -iv $encrypted_9dc66686a9e7_iv
  -in multi-k8s-268707-82ef7e71f613.json.enc -out ~\/.gcloud/multi-k8s-268707-82ef7e71f613.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
