sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9dc66686a9e7_key -iv $encrypted_9dc66686a9e7_iv -in multi-k8s-268707-82ef7e71f613.json.enc -out multi-k8s-268707-82ef7e71f613.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-268707-82ef7e71f613.json
  - gcloud config set project multi-k8s-268707
  - gcloud config set compute/zone europe-west3-c
  - gcloud container clusters get-credentials multi-cluster
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t sorinlacriteanu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sorinlacriteanu/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
